### PR TITLE
Update Python version to test based on the EOL status.

### PR DESCRIPTION
**Pull request by hrchu**
ref https://endoflife.date/python

### CODE REVIEW

**Comment by hrchu** [comment]
Seems setuptools in not available in 3.12. I'll check it out later.

**Comment by peter0083** [comment]
sounds good. thanks for the update!

**Comment by hrchu** [comment]
@peter0083 issue fixed. Merge it if you feel comfortable with plz.

**Comment by peter0083** [comment]
all good!

**Pull request merged**
