### PR TITLE
Clarify that it only works with NSS

### PR DESCRIPTION
**Pull request by Otto-AA**
Looking at auth.py this project relies on a `/login/password` endpoint and the `nssidp.sid` cookie. I think both of these are not standardized and only work with NSS (at least **nss**idp.sid suggests it is NSS specific).

It would make sense to clarify this in the README so users don't get wrong expectations (as in #30).

### CODE REVIEW

**Comment by hrchu** [comment]
LGTM. @peter0083 could you merge this PR if you feel comfortable with it?

**Comment by hrchu** [comment]
Solid authentication standard is not ready to use in production back to two years ago (see issue #3 ). The basic auth we implemented was the only way to do authentication at that time (except javascript libs).

We actually mentioned the limitation clearly in the document (see the `Access private resources` in https://github.com/twonote/solid-file-python/blob/master/solid-file-python-getting-start.ipynb)

However, it is nice to see the limitation more clearly from the user's perspective.

**Comment by hrchu** [comment]
@Otto-AA would you like to contribute to `Solid-OIDC` support for the Python ecosystem? I believe it can make a huge impact 
 both on Solid and Python communities.

**Comment by Otto-AA** [comment]
Thanks for the quick responses!

> @Otto-AA would you like to contribute to Solid-OIDC support for the Python ecosystem? I believe it can make a huge impact both on Solid and Python communities.

If I have time sure, but I don't know when this will be :upside_down_face: 

In the meantime, you could look into:
- [solid-flask](https://gitlab.com/agentydragon/solid-flask/): this implemented Solid-OIDC. It works with NSS but is bugged with ESS, I don't know yet what's the error cause.
- [SolidClientCredentials](https://solid-client-credentials.readthedocs.io/en/latest/): login with non-standardized client credentials (can be used via ESS or CSS only). I've written it with `requests` in mind, not sure how easy it is to use the tokens for `httpx`. If you want help here, feel free to ask.

**Comment by Otto-AA** [comment]
Regarding solid-flask, I've made a [merge request](https://gitlab.com/agentydragon/solid-flask/-/merge_requests/1) there that fixes the problems with ESS. So it now has a working demo for Solid-OIDC (at least for ESS, CSS and NSS).

**Comment by renyuneyun** [comment]
There is also this project for Solid OIDC, which seems to be more complete?: https://github.com/trompamusic/solid-oidc-app-permission

**Comment by Otto-AA** [comment]
> ~There is also this Python project for Solid OIDC, which seems to be more complete?: https://github.com/trompamusic/solid-oidc-app-permission~
Never mind. That project seems to be a server implementation/mockup, not client.

As mentioned in the [forum thread](https://forum.solidproject.org/t/authentication-solid-oidc-implementation-in-python-and-beyond/7004), I think it acts as a client for the Solid OIDC protocol, ie it is not an identity provider, but tries to login a user to an existing IDP through Solid-OIDC.

**Comment by renyuneyun** [comment]
Just for information: I created a PR #38 which integrates solid-oidc-client with this library. It's working, but not entirely complete as of the discussion points.

**Comment by peter0083** [comment]
Looks good to me. Merging this PR. Thank you for your contribution @renyuneyun !

**Pull request merged**
